title: "NanoNova's cyberspace"
description: The ubiquitous uniqueness

locals:
  /:
    lang: zh-CN
  /en/:
    lang: en-US

themeConfig:
  logo: /img/logo.jpeg
  sidebar: auto
  lastUpdated: true
  smoothScroll: true
  locals:
    /:
      selectText: ğŸŒ
      label: ä¸­æ–‡
      nav:
        - text: å‰ç«¯
          link: /frontend
        - text: åç«¯
          link: /backend
          items:
            - text: xx
              link: /backend/xx
            - text: hh
              link: /backend/hh
    /en/:
      selectText: ğŸŒi18n
      label: English
      nav:
        - text: Frontend
          link: /frontend
        - text: Backend
          link: /backend
          items:
            - text: xx
              link: /backend/xx
            - text: hh
              link: /backend/hh
