title: "NanoNova's cyberspace"
description: The ubiquitous uniqueness
head:
  - - link
    - rel: icon
      href: /img/logo.png
  - - link
    - rel: manifest
      href: /manifest.json

markdown:
  lineNumbers: true

locales:
  /:
    lang: zh-CN
  /en/:
    lang: en-US

plugins:
  '@vuepress/back-to-top': ~
  '@vuepress/medium-zoom':
    options:
      margin: 20
  '@vuepress/pwa':
    serviceWorker: true
    updatePopup: true
  'img-lazy': ~
  'flowchart': ~
  'feed':
    canonical_base: 'https://nanonova.space'
    posts_directories:
      - /

themeConfig:
  logo: /img/logo.png
  sidebar: auto
  lastUpdated: true
  smoothScroll: true
  locales:
    /:
      selectText: ğŸŒ
      label: ğŸ‡¨ğŸ‡³ä¸­æ–‡
      nav:
        - text: å‰ç«¯
          link: /frontend
        - text: åç«¯
          link: /backend
          items:
            - text: xx
              link: /backend/xx
            - text: hh
              link: /backend/hh
    /en/:
      selectText: ğŸŒ
      label: ğŸ‡ºğŸ‡¸English
      nav:
        - text: Frontend
          link: /frontend
        - text: Backend
          link: /en/backend
          items:
            - text: be
              link: /en/backend/be
            - text: hh
              link: /en/backend/hh
